kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: js-school.cr.cloud.ru/js-school-frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "150m"
          env:
            - name: REACT_APP_backend_host
              value: "95.174.89.37"
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
